import bcrypt from 'bcryptjs'
import fs from 'node:fs'
import path from 'node:path'
import { get, run, now } from './index.js'
import { createLead, getLead, nextVersionForItem, activateReachedStep } from '../services/leads.js'
import { logHistory } from '../services/history.js'
import { UPLOAD_DIR } from '../middleware/upload.js'
import { findGate, findItem, nextGate, type GateKey, type Role } from '../config/stageGates.js'

type SeedUser = { username: string; full_name: string; role: Role; client_company?: string; is_team_head?: boolean }

const DEMO_PASSWORD = 'Kavis@123'

const USERS: SeedUser[] = [
  // BD: Vinay executes Step 1; Neha is BD Team Head — both get full CDA detail.
  { username: 'bd.vinay', full_name: 'Vinay Kulkarni', role: 'business_development' },
  { username: 'bd.head', full_name: 'Neha Patil — BD Team Head', role: 'business_development', is_team_head: true },
  { username: 'safety.ananya', full_name: 'Ananya Rao', role: 'safety', is_team_head: true },
  { username: 'mfg.suresh', full_name: 'Suresh Iyer', role: 'manufacturing', is_team_head: true },
  { username: 'analytical.priya', full_name: 'Priya Menon', role: 'analytical', is_team_head: true },
  { username: 'quality.karthik', full_name: 'Karthik Nair', role: 'quality', is_team_head: true },
  { username: 'costing.deepa', full_name: 'Deepa Shah', role: 'costing', is_team_head: true },
  { username: 'regulatory.farah', full_name: 'Farah Sheikh', role: 'regulatory', is_team_head: true },
  { username: 'legal.advait', full_name: 'Advait Deshmukh', role: 'legal', is_team_head: true },
  { username: 'supplychain.rohan', full_name: 'Rohan Kapoor', role: 'supply_chain', is_team_head: true },
  { username: 'rd.meera', full_name: 'Meera Pillai', role: 'rd', is_team_head: true },
  { username: 'engineering.arjun', full_name: 'Arjun Verma', role: 'engineering', is_team_head: true },
  { username: 'sr.rajesh', full_name: 'Rajesh Kumar — Senior Management', role: 'senior_management' },
  { username: 'client.meridian', full_name: 'Meridian Health — Client Contact', role: 'client', client_company: 'Meridian Health' },
  { username: 'client.solara', full_name: 'Solara Pharma — Client Contact', role: 'client', client_company: 'Solara Pharma' },
]

async function ensureUsers(): Promise<Record<string, number>> {
  const ts = now()
  const hash = bcrypt.hashSync(DEMO_PASSWORD, 10)
  const ids: Record<string, number> = {}
  for (const u of USERS) {
    const existing = await get<{ id: number }>('SELECT id FROM users WHERE username = ?', [u.username])
    if (existing) {
      ids[u.username] = existing.id
      // Keep team-head flag in sync for existing DBs so ACL demos stay accurate.
      await run('UPDATE users SET is_team_head = ?, updated_at = ? WHERE id = ?', [u.is_team_head ? 1 : 0, ts, existing.id])
      continue
    }
    const info = await run(`
      INSERT INTO users (username, password, full_name, role, client_company, is_admin, is_team_head, activated, must_change_password, created_at, updated_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, 1, 1, ?, ?)
    `, [
      u.username, hash, u.full_name, u.role, u.client_company || null,
      u.role === 'senior_management' ? 1 : 0, u.is_team_head ? 1 : 0, ts, ts,
    ])
    ids[u.username] = info.insertId
    console.log(`Created user: ${u.username} (${u.role}${u.is_team_head ? ', team head' : ''})`)
  }
  return ids
}

// --- helpers that mirror the real route logic, for building a realistic demo pipeline ---

function writePlaceholderFile(storedFilename: string, label: string) {
  const filePath = path.join(UPLOAD_DIR, storedFilename)
  const body = `%PDF-1.4\n% Placeholder demo document\n% ${label}\n% Generated by db/seed.ts for interface review — not a real CDMO document.\n`
  fs.writeFileSync(filePath, body)
}

async function seedSubmit(leadId: number, gate: GateKey, itemKey: string, byUserId: number, remarks: string, withDoc: boolean) {
  const item = findItem(gate, itemKey)!
  const row = await get<{ id: number }>('SELECT id FROM lead_items WHERE lead_id = ? AND item_key = ?', [leadId, itemKey])
  if (!row) return
  const ts = now()
  await run(`
    UPDATE lead_items SET status = 'submitted', doc_required = ?, remarks = ?, submitted_by = ?, submitted_at = ?, updated_at = ?
    WHERE id = ?
  `, [item.docRequired ? 1 : 0, remarks, byUserId, ts, ts, row.id])
  if (withDoc && item.docRequired) {
    const version = await nextVersionForItem(row.id)
    const storedFilename = `seed-${leadId}-${itemKey}-v${version}.pdf`
    const originalFilename = `${item.label}.pdf`
    writePlaceholderFile(storedFilename, originalFilename)
    await run(`
      INSERT INTO lead_documents (lead_item_id, version, original_filename, stored_filename, mime_type, size_bytes, uploaded_by, uploaded_at)
      VALUES (?, ?, ?, ?, 'application/pdf', ?, ?, ?)
    `, [row.id, version, originalFilename, storedFilename, fs.statSync(path.join(UPLOAD_DIR, storedFilename)).size, byUserId, ts])
  }
}

async function seedApprove(leadId: number, gate: GateKey, itemKey: string, byUserId: number, comments: string) {
  const row = await get<{ id: number }>('SELECT id FROM lead_items WHERE lead_id = ? AND item_key = ?', [leadId, itemKey])
  if (!row) return
  const ts = now()
  await run(`UPDATE lead_items SET status = 'approved', approved_by = ?, approved_at = ?, approval_comments = ?, updated_at = ? WHERE id = ?`, [byUserId, ts, comments, ts, row.id])
  await activateReachedStep(leadId, gate)
}

async function seedGateApprove(leadId: number, gate: GateKey, byUserId: number, comments: string) {
  const ts = now()
  await run(`INSERT INTO gate_approvals (lead_id, gate, approved_by, approved_at, comments) VALUES (?, ?, ?, ?, ?)`, [leadId, gate, byUserId, ts, comments])
  const next = nextGate(gate)
  if (next) {
    await run(`UPDATE leads SET current_gate = ?, updated_at = ? WHERE id = ?`, [next, ts, leadId])
    await activateReachedStep(leadId, next)
  } else {
    await run(`UPDATE leads SET status = 'completed', updated_at = ? WHERE id = ?`, [ts, leadId])
  }
}

async function seedCompleteGate(leadId: number, gate: GateKey, byUserId: number) {
  const gateDef = findGate(gate)!
  for (const item of gateDef.items) {
    const row = await get<{ status: string }>('SELECT status FROM lead_items WHERE lead_id = ? AND item_key = ?', [leadId, item.key])
    if (row && row.status !== 'not_applicable') {
      await seedSubmit(leadId, gate, item.key, byUserId, `${item.label} on file.`, item.docRequired)
      await seedApprove(leadId, gate, item.key, byUserId, 'Verified and approved.')
    }
  }
  await seedGateApprove(leadId, gate, byUserId, `${gateDef.name} — all mandatory items verified.`)
}

export async function seed() {
  const existingUsers = await get<{ c: number }>('SELECT COUNT(*) as c FROM users')
  const u = await ensureUsers()

  const existingLeads = await get<{ c: number }>('SELECT COUNT(*) as c FROM leads')
  if (Number(existingLeads?.c || 0) > 0) {
    console.log(`Database already has ${existingLeads?.c} lead(s) — skipping demo data`)
  } else {
    const bdActor = { id: u['bd.vinay'], full_name: 'Vinay Kulkarni' }
    const srActor = { id: u['sr.rajesh'], full_name: 'Rajesh Kumar' }

    // Lead A — mid-RFP, one item awaiting Senior Management approval, others still open for Costing/Engineering
    const leadA = await createLead({ product: 'Atomoxetine Oral Solution', strength: '4 mg/mL', dosageForm: 'Oral Solution', clientName: 'Meridian Health', clientCountry: 'Kenya', priority: 'High' }, bdActor as any)
    await seedCompleteGate(leadA, 'rfi', u['sr.rajesh'])
    await seedSubmit(leadA, 'rfp', 'sow', u['bd.vinay'], 'Scope of work agreed with client procurement.', true)
    await seedApprove(leadA, 'rfp', 'sow', u['sr.rajesh'], 'Confirmed against RFI intake.')
    await seedSubmit(leadA, 'rfp', 'cleaning_method', u['quality.karthik'], 'Swab + rinse method proposed, validated on similar oral solutions.', true)
    await seedApprove(leadA, 'rfp', 'cleaning_method', u['sr.rajesh'], 'Aligned with existing validation master plan.')
    await seedSubmit(leadA, 'rfp', 'costing_buildup', u['costing.deepa'], 'COGS build-up submitted for Senior Management review.', true)
    await logHistory(leadA, srActor, 'Note', 'Engineering and remaining Quality/Analytical items are still open in RFP — visible on their pending dashboards.')

    // Lead B — reached Agreement gate, then an RFP item was sent back (demonstrates gate reopening)
    const leadB = await createLead({ product: 'Metformin HCl ER Tablets', strength: '500 mg', dosageForm: 'Tablet', clientName: 'Solara Pharma', clientCountry: 'Philippines', priority: 'Standard' }, bdActor as any)
    await seedCompleteGate(leadB, 'rfi', u['sr.rajesh'])
    await seedCompleteGate(leadB, 'rfp', u['sr.rajesh'])
    {
      const row = await get<{ id: number }>('SELECT id FROM lead_items WHERE lead_id = ? AND item_key = ?', [leadB, 'excipient_spec_rfp'])
      const ts = now()
      await run(`UPDATE lead_items SET status = 'sent_back', approved_by = NULL, approved_at = NULL, approval_comments = NULL, activated_at = NULL, updated_at = ? WHERE id = ?`, [ts, row!.id])
      await run(`UPDATE gate_approvals SET superseded = 1 WHERE lead_id = ? AND gate = 'rfp' AND superseded = 0`, [leadB])
      await run(`UPDATE leads SET current_gate = 'rfp', status = 'active', updated_at = ? WHERE id = ?`, [ts, leadB])
      await activateReachedStep(leadB, 'rfp')
      await logHistory(leadB, srActor, 'Sent Back', '"Excipient Specification, CoA & MSDS" (Stage 2 — RFP) sent back by Rajesh Kumar — client swapped their excipient supplier after Agreement drafting began; specs need re-verification. This reopens the gate approval for this stage.')
    }

    // Lead C — fully completed, all 3 gates approved
    const leadC = await createLead({ product: 'Losartan Potassium Tablets', strength: '50 mg', dosageForm: 'Tablet', clientName: 'Northbridge Biotech', clientCountry: 'Vietnam', priority: 'High' }, bdActor as any)
    await seedCompleteGate(leadC, 'rfi', u['sr.rajesh'])
    await seedCompleteGate(leadC, 'rfp', u['sr.rajesh'])
    await seedCompleteGate(leadC, 'agreement', u['sr.rajesh'])

    // Lead D — on hold, mid-Agreement
    const leadD = await createLead({ product: 'Cetirizine HCl Oral Syrup', strength: '5 mg/5 mL', dosageForm: 'Syrup', clientName: 'Vantage Rx', clientCountry: 'United Arab Emirates', priority: 'Standard' }, bdActor as any)
    await seedCompleteGate(leadD, 'rfi', u['sr.rajesh'])
    await seedCompleteGate(leadD, 'rfp', u['sr.rajesh'])
    await seedSubmit(leadD, 'agreement', 'loi_msa_qta', u['legal.advait'], 'LOI and MSA drafts circulated to client legal team.', true)
    await seedApprove(leadD, 'agreement', 'loi_msa_qta', u['sr.rajesh'], 'Terms consistent with approved RFP.')
    {
      const ts = now()
      await run(`UPDATE leads SET status = 'on_hold', hold_reason = ?, updated_at = ? WHERE id = ?`, ["Client's parent entity is undergoing a regulatory inspection abroad; management asked to pause new contracting until cleared.", ts, leadD])
      await logHistory(leadD, srActor, 'Placed On Hold', "Client's parent entity is undergoing a regulatory inspection abroad; management asked to pause new contracting until cleared.")
    }

    // Lead E — dropped during RFI
    const leadE = await createLead({ product: 'Paracetamol Oral Solution', strength: '250 mg/5 mL', dosageForm: 'Oral Solution', clientName: 'Ashgrove Pharma', clientCountry: 'Nigeria', priority: 'Standard' }, bdActor as any)
    await seedSubmit(leadE, 'rfi', 'cda', u['bd.vinay'], 'CDA sent to client for countersignature.', true)
    {
      const ts = now()
      await run(`UPDATE leads SET status = 'dropped', drop_reason = ?, updated_at = ? WHERE id = ?`, ['Client declined to accept mutual confidentiality terms and requested a one-sided NDA outside policy; escalated and closed.', ts, leadE])
      await logHistory(leadE, bdActor as any, 'Dropped', 'Lead dropped at Stage 1 — RFI — Client declined to accept mutual confidentiality terms and requested a one-sided NDA outside policy; escalated and closed.')
    }

    // Lead F — fresh, nothing submitted yet, same client as Lead A (client.meridian can see 2 leads)
    await createLead({ product: 'Omeprazole DR Capsules', strength: '20 mg', dosageForm: 'Capsule', clientName: 'Meridian Health', clientCountry: 'Kenya', priority: 'Standard' }, bdActor as any)

    // Lead G — potent molecule, exercises the conditional Safety item
    await createLead({ product: 'Tamsulosin Modified-Release Pellets', strength: '0.4 mg', dosageForm: 'Pellets (capsule fill)', clientName: 'Solara Pharma', clientCountry: 'Philippines', priority: 'High', potentMolecule: true }, bdActor as any)

    console.log('Seeded 7 demo leads across RFI / RFP / Agreement, including hold, drop, send-back and completed cases.')
  }

  console.log('\nDemo logins (all use the same password):')
  console.log(`  Password for every seeded account: ${DEMO_PASSWORD}\n`)
  for (const u2 of USERS) console.log(`  ${u2.username.padEnd(20)} ${u2.role}${u2.client_company ? ` (${u2.client_company})` : ''}`)
  if (Number(existingUsers?.c || 0) > 0) console.log('\n(Users already existed — passwords were not reset.)')
}

const isDirect = process.argv[1]?.includes('seed')
if (isDirect) {
  seed().then(() => process.exit(0)).catch((err) => { console.error(err); process.exit(1) })
}
